name: Deploy to cPanel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo
    
    - name: Install PHP Dependencies
      run: composer install --no-dev --optimize-autoloader
    
    - name: Install Node Dependencies
      run: npm ci
    
    - name: Build Assets
      run: npm run build
    
    - name: Create production .env
      run: |
        cp .env.production .env
        php artisan key:generate --force
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache
    
    - name: Deploy to cPanel via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /public_html/shalom-erp/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/tests/**
          **/.env.example
          **/.env.local
          **/README.md
          **/package*.json
          **/vite.config.js
          **/composer.json
          **/composer.lock
          **/phpunit.xml
